"""empty message

Revision ID: 2590c3e1aaf1
Revises: 4f3eb8837100
Create Date: 2025-08-10 08:56:52.985827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2590c3e1aaf1'
down_revision = '4f3eb8837100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('edited', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('gravity')
        batch_op.drop_column('population')
        batch_op.drop_column('diameter')

    # ### end Alembic commands ###
