"""empty message

Revision ID: 4f3eb8837100
Revises: e31e55695438
Create Date: 2025-08-10 08:51:30.166249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3eb8837100'
down_revision = 'e31e55695438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starship_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cost_in_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hyperdrive_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('MGLT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('edited', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('MGLT')
        batch_op.drop_column('hyperdrive_rating')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('consumables')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('passengers')
        batch_op.drop_column('starship_class')

    # ### end Alembic commands ###
